#ifndef PLATING_UTILS_LOG_LEVELS_H
#define PLATING_UTILS_LOG_LEVELS_H

#define LOG_LEVEL_ERROR 2
#define LOG_LEVEL_WARN 1
#define LOG_LEVEL_INFO 0
#define LOG_LEVEL_DEBUG -1
#define LOG_LEVEL_TRACE -2
#define LOG_LEVEL_DEEP_TRACE -3

#endif // PLATING_UTILS_LOG_LEVELS_H